production:
  sessions:
    default:
      database: botonera-game
      hosts:
        - localhost:27017
development:
  sessions:
    default:
      database: botonera-game
      hosts:
        - localhost:27017
